# Blog engine config file

# General
#name: Your blog name
#description: describe your blog here

# Post repo
#repo:
#  name: posts
#  path: /
#  url: your git address
#  key: yoursecretkey

# Comments with disqus
#disqus:
#  shortname: yourshortname
#  debug: true # enable that in testing environment
