# Blog engine config file

# General
#name: Your blog name
#description: describe your blog here

# Post repo
#repo:
  #name: posts
  #path: /
  #url: yourgiturl
  #key: yoursecretkey

# Comments with disqus
#disqus:
#  shortname: yourshortname
