# Blog engine config file
name: kurt's blog
description: build on his new git based blog engine :)
base:
repositories:
  - git@github.com:garnieretienne/install_puppet.git
  - git@github.com:garnieretienne/yuback.git
