# Blog engine config file

# General
name: Yublog
description: kurt's blog

# Post repo
repo:
  name: posts
  path: /
  url: git@github.com:garnieretienne/kurt.yuweb.fr.git
  key: z8Diy5w1fn42iW

# Comments with disqus
#disqus:
#  shortname: yourshortname
#  debug: true # enable that in testing environment
